#!/bin/bash
#SBATCH --job-name=truncations
#SBATCH --partition=highmem_p
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=30
#SBATCH --mem=455G
#SBATCH --time=24:00:00
#SBATCH --export=NONE
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ul54354@uga.edu
# Absolute path to the DNA_sequence.qza file
FILE_PATH="/home/ul54354/DNA_sequence.qza"
cd $SLURM_SUBMIT_DIR
export LC_ALL=en_US.UTF-8
ml QIIME2/2023.2
# First denoising run without truncations
mkdir -p /lscratch/$ul54354/$SLURM_JOB_ID
cp -R $FILE_PATH /lscratch/$ul54354/$SLURM_JOB_ID
cd /lscratch/$ul54354/$SLURM_JOB_ID
if [[ -f DNA_sequence.qza ]]; then
    qiime dada2 denoise-paired \
    --i-demultiplexed-seqs DNA_sequence.qza \
    --p-trunc-len-f 0 \
    --p-trunc-len-r 0 \
    --p-trim-left-f 20 \
    --p-trim-left-r 24 \
    --p-n-threads 0 \
    --o-table table_0.qza \
    --o-representative-sequences rep_seqs_0.qza \
    --o-denoising-stats dada2_stats_0.qza
    cp -R table_0.qza $SLURM_SUBMIT_DIR
    cp -R rep_seqs_0.qza $SLURM_SUBMIT_DIR
    cp -R dada2_stats_0.qza $SLURM_SUBMIT_DIR
    rm -r -f /lscratch/$ul54354/$SLURM_JOB_ID
else
    echo "Error: DNA_sequence.qza not found in /lscratch/$ul54354/$SLURM_JOB_ID"
    exit 1
fi
# Denoising for the combinations f_245 to f_248 and r_234 to r_241  and the trims are f_20 and r_24
for trunc_f in {245..248}; do
    for trunc_r in {234..241}; do
        FILE_SUFFIX="f${trunc_f}_r${trunc_r}"
        mkdir -p /lscratch/$ul54354/$SLURM_JOB_ID
        cp -R $FILE_PATH /lscratch/$ul54354/$SLURM_JOB_ID
        cd /lscratch/$ul54354/$SLURM_JOB_ID
        if [[ -f DNA_sequence.qza ]]; then
            qiime dada2 denoise-paired \
            --i-demultiplexed-seqs DNA_sequence.qza \
            --p-trunc-len-f $trunc_f \
            --p-trunc-len-r $trunc_r \
            --p-trim-left-f 20 \
            --p-trim-left-r 24 \
            --p-n-threads 0 \
            --o-table table_${FILE_SUFFIX}.qza \
            --o-representative-sequences rep_seqs_${FILE_SUFFIX}.qza \
            --o-denoising-stats dada2_stats_${FILE_SUFFIX}.qza
            cp -R table_${FILE_SUFFIX}.qza $SLURM_SUBMIT_DIR
            cp -R rep_seqs_${FILE_SUFFIX}.qza $SLURM_SUBMIT_DIR
            cp -R dada2_stats_${FILE_SUFFIX}.qza $SLURM_SUBMIT_DIR
            rm -r -f /lscratch/$ul54354/$SLURM_JOB_ID
        else
            echo "Error: DNA_sequence.qza not found in /lscratch/$ul54354/$SLURM_JOB_ID for truncation f=$trunc_f r=$trunc_r"
            exit 1
        fi
    done
done
cd $SLURM_SUBMIT_DIR

#I used my user: ul54354 where you can use your server username 


